# Site settings
title: Disruptive Bias
email: randy-REMOVE-bias@-gee-mail.com
description: "The upcoming location of my new personal blog on all things disruptive: technology, games, politics, and life lessons."
baseurl: ""
url: "http://disruptivebias.com"
twitter_username: randybias
github_username:  randybias

# Build settings
markdown: kramdown
permalink: pretty
